TEMPLATE = app
TARGET = QOverlordApp
QT += core \
    gui \
    network \
    webkit
HEADERS += engine/combat/BasicCombatEngine.h \
    engine/combat/BasicCombatManager.h \
    engine/combat/BasicCombatRequest.h \
    engine/combat/BattleEntity.h \
    engine/combat/BattleField.h \
    engine/combat/BattleInstance.h \
    engine/combat/BattleUnit.h \
    engine/combat/CombatEngine.h \
    engine/combat/CombatManager.h \
    engine/combat/CombatOrderProcessor.h \
    engine/combat/CombatTactics.h \
    engine/combat/GuardingRequest.h \
    engine/combat/PillageRequest.h \
    engine/combat/actions/MeleeCombatAction.h \
    engine/combat/actions/RangedCombatAction.h \
    engine/combat/actions/SpecialCombatAction.h \
    engine/combat/orders/AdvanceCombatOrder.h \
    engine/combat/orders/ApplyCombatOrder.h \
    engine/combat/orders/ChargeCombatOrder.h \
    engine/combat/orders/CombatOrderPrototype.h \
    engine/combat/orders/FireCombatOrder.h \
    engine/combat/orders/FlankCombatOrder.h \
    engine/combat/orders/FleeCombatOrder.h \
    engine/combat/orders/MeleeCombatOrder.h \
    engine/combat/orders/MoveCombatOrder.h \
    engine/combat/orders/ParryCombatOrder.h \
    engine/combat/orders/RangedCombatOrder.h \
    engine/combat/orders/RetreatCombatOrder.h \
    engine/combat/orders/StandCombatOrder.h \
    engine/combat/orders/SupportCombatOrder.h \
    engine/combat/orders/SweepCombatOrder.h \
    engine/combat/orders/UseCombatOrder.h \
    engine/datatypes/AbstractData.h \
    engine/datatypes/BasicData.h \
    engine/datatypes/GameData.h \
    engine/datatypes/IntegerData.h \
    engine/datatypes/PrototypeManager.h \
    engine/datatypes/RationalNumber.h \
    engine/datatypes/StringData.h \
    engine/datatypes/attributes/BasicAttribute.h \
    engine/datatypes/attributes/EnchantmentAttribute.h \
    engine/datatypes/attributes/InventoryAttribute.h \
    engine/datatypes/attributes/MovementBonusAttribute.h \
    engine/datatypes/attributes/OwnershipPolicyAttribute.h \
    engine/datatypes/attributes/PermissionAttribute.h \
    engine/datatypes/attributes/SkillBonusAttribute.h \
    engine/datatypes/attributes/SkillBonusComboAttribute.h \
    engine/datatypes/attributes/SkillsAttribute.h \
    engine/datatypes/attributes/TitlesAttribute.h \
    engine/datatypes/collections/BasicCollection.h \
    engine/datatypes/collections/BasicEntitiesCollection.h \
    engine/datatypes/collections/BasicRulesCollection.h \
    engine/datatypes/collections/BasicVarietiesCollection.h \
    engine/datatypes/collections/DataStorageHandler.h \
    engine/datatypes/collections/EntitiesCollection.h \
    engine/datatypes/collections/MovementMode.h \
    engine/datatypes/collections/OrderPrototypesCollection.h \
    engine/datatypes/collections/RulesCollection.h \
    engine/datatypes/collections/VarietiesCollection.h \
    engine/datatypes/conditions/BasicCondition.h \
    engine/datatypes/conditions/ObservationCondition.h \
    engine/datatypes/conditions/SkillCondition.h \
    engine/datatypes/elements/BonusElement.h \
    engine/datatypes/elements/ConstructionWorksElement.h \
    engine/datatypes/elements/Element.h \
    engine/datatypes/elements/EnchantmentElement.h \
    engine/datatypes/elements/FactionPermissionElement.h \
    engine/datatypes/elements/InventoryElement.h \
    engine/datatypes/elements/ItemElement.h \
    engine/datatypes/elements/MeleeAttackElement.h \
    engine/datatypes/elements/MovementBonusElement.h \
    engine/datatypes/elements/MovementElement.h \
    engine/datatypes/elements/PermissionElement.h \
    engine/datatypes/elements/RaceElement.h \
    engine/datatypes/elements/ReportElement.h \
    engine/datatypes/elements/ResourceElement.h \
    engine/datatypes/elements/SkillElement.h \
    engine/datatypes/elements/SkillLevelElement.h \
    engine/datatypes/elements/SkillUseElement.h \
    engine/datatypes/elements/StanceElement.h \
    engine/datatypes/elements/TitleElement.h \
    engine/datatypes/elements/ToolUseElement.h \
    engine/datatypes/elements/TravelElement.h \
    engine/datatypes/elements/TreeBonusElement.h \
    engine/datatypes/elements/WeatherElement.h \
    engine/datatypes/entities/ConstructionEntity.h \
    engine/datatypes/entities/EffectEntity.h \
    engine/datatypes/entities/Entity.h \
    engine/datatypes/entities/FactionEntity.h \
    engine/datatypes/entities/LocationEntity.h \
    engine/datatypes/entities/TokenEntity.h \
    engine/datatypes/entities/UnitEntity.h \
    engine/datatypes/misc/BasicExit.h \
    engine/datatypes/misc/EntityStatistics.h \
    engine/datatypes/misc/ExplicitExit.h \
    engine/datatypes/misc/NewEntityPlaceholder.h \
    engine/datatypes/misc/OwnershipPolicy.h \
    engine/datatypes/rules/ActionRule.h \
    engine/datatypes/rules/ConstructionRule.h \
    engine/datatypes/rules/CreatureRaceRule.h \
    engine/datatypes/rules/EnchantmentRule.h \
    engine/datatypes/rules/FollowerRaceRule.h \
    engine/datatypes/rules/ItemRule.h \
    engine/datatypes/rules/LeaderRaceRule.h \
    engine/datatypes/rules/RaceRule.h \
    engine/datatypes/rules/Rule.h \
    engine/datatypes/rules/RuleIndex.h \
    engine/datatypes/rules/SeasonRule.h \
    engine/datatypes/rules/SkillRule.h \
    engine/datatypes/rules/TerrainRule.h \
    engine/datatypes/rules/TitleRule.h \
    engine/datatypes/rules/WeatherRule.h \
    engine/datatypes/strategies/ActionUsingStrategy.h \
    engine/datatypes/strategies/BasicLearningStrategy.h \
    engine/datatypes/strategies/BasicProductionStrategy.h \
    engine/datatypes/strategies/BasicUsingStrategy.h \
    engine/datatypes/strategies/BuildUsingStrategy.h \
    engine/datatypes/strategies/CombatActionStrategy.h \
    engine/datatypes/strategies/CombatUsingStrategy.h \
    engine/datatypes/strategies/ConstructionUsingStrategy.h \
    engine/datatypes/strategies/CraftUsingStrategy.h \
    engine/datatypes/strategies/CreatureLearningStrategy.h \
    engine/datatypes/strategies/EnchantmentUsingStrategy.h \
    engine/datatypes/strategies/HarvestUsingStrategy.h \
    engine/datatypes/strategies/MagicLearningStrategy.h \
    engine/datatypes/strategies/MarketStrategy.h \
    engine/datatypes/strategies/NormalLearningStrategy.h \
    engine/datatypes/strategies/Strategy.h \
    engine/datatypes/strategies/SummonUsingStrategy.h \
    engine/datatypes/varieties/CombatFileVariety.h \
    engine/datatypes/varieties/CombatMoveVariety.h \
    engine/datatypes/varieties/CombatRankVariety.h \
    engine/datatypes/varieties/CombatStanceVariety.h \
    engine/datatypes/varieties/CombatTargetVariety.h \
    engine/datatypes/varieties/ConstructionWorksVariety.h \
    engine/datatypes/varieties/DirectionVariety.h \
    engine/datatypes/varieties/EquipmentSlotVariety.h \
    engine/datatypes/varieties/MovementVariety.h \
    engine/datatypes/varieties/StanceVariety.h \
    engine/datatypes/varieties/Variety.h \
    engine/implementation/actions/PickpocketActionRule.h \
    engine/implementation/combat/EnchantCombatAction.h \
    engine/implementation/combat/HeavinessCombatAction.h \
    engine/implementation/combat/SummonCombatAction.h \
    engine/misc/FileParser.h \
    engine/misc/LineParser.h \
    engine/misc/OverlordTypes.h \
    engine/misc/ReportPrinter.h \
    engine/misc/Symbols.h \
    engine/misc/SystemTypes.h \
    engine/misc/dgChannelBuf.h \
    engine/process/CombatOrderLine.h \
    engine/process/OrderLine.h \
    engine/process/OrderProcessor.h \
    engine/process/ProcessingMode.h \
    engine/process/conflicts/BasicCompetitiveRequest.h \
    engine/process/conflicts/BasicConflict.h \
    engine/process/conflicts/BasicRequest.h \
    engine/process/conflicts/EvenConflict.h \
    engine/process/conflicts/LocalMarketRequest.h \
    engine/process/conflicts/LocalRecruitOffer.h \
    engine/process/conflicts/MarketConflict.h \
    engine/process/conflicts/MarketRequest.h \
    engine/process/conflicts/NewRecruitRequest.h \
    engine/process/conflicts/RecruitRequest.h \
    engine/process/conflicts/ResourceCompetitiveRequest.h \
    engine/process/conflicts/TeachingOffer.h \
    engine/process/conflicts/WagesCompetitiveRequest.h \
    engine/process/orders/AcceptOrder.h \
    engine/process/orders/AtOrder.h \
    engine/process/orders/AttackOrder.h \
    engine/process/orders/BasicOrderSynchronizationRequest.h \
    engine/process/orders/BestowOrder.h \
    engine/process/orders/BuildOrder.h \
    engine/process/orders/BuyOrder.h \
    engine/process/orders/CancelOrder.h \
    engine/process/orders/CaravanOrder.h \
    engine/process/orders/ChristenOrder.h \
    engine/process/orders/ClaimOrder.h \
    engine/process/orders/CombatOrder.h \
    engine/process/orders/DayOrder.h \
    engine/process/orders/DescribeOrder.h \
    engine/process/orders/DisbandOrder.h \
    engine/process/orders/DropOrder.h \
    engine/process/orders/EjectOrder.h \
    engine/process/orders/EmailOrder.h \
    engine/process/orders/EnterOrder.h \
    engine/process/orders/EquipOrder.h \
    engine/process/orders/ExitOrder.h \
    engine/process/orders/ForgetOrder.h \
    engine/process/orders/GetOrder.h \
    engine/process/orders/GiveOrder.h \
    engine/process/orders/GuardOrder.h \
    engine/process/orders/HaveOrder.h \
    engine/process/orders/LeaderOrder.h \
    engine/process/orders/LeadingOrder.h \
    engine/process/orders/LeaveOrder.h \
    engine/process/orders/MarchOrder.h \
    engine/process/orders/MergeOrder.h \
    engine/process/orders/MoveOrder.h \
    engine/process/orders/NameOrder.h \
    engine/process/orders/OathOrder.h \
    engine/process/orders/OrderPrototype.h \
    engine/process/orders/PasswordOrder.h \
    engine/process/orders/PatrolOrder.h \
    engine/process/orders/PillageOrder.h \
    engine/process/orders/PromoteOrder.h \
    engine/process/orders/RecruitOrder.h \
    engine/process/orders/ReshowOrder.h \
    engine/process/orders/ResignOrder.h \
    engine/process/orders/RetreatOrder.h \
    engine/process/orders/SeeOrder.h \
    engine/process/orders/SellOrder.h \
    engine/process/orders/SettingOrder.h \
    engine/process/orders/SizeOrder.h \
    engine/process/orders/SkillOrder.h \
    engine/process/orders/SplitOrder.h \
    engine/process/orders/StackOrder.h \
    engine/process/orders/StanceOrder.h \
    engine/process/orders/StayOrder.h \
    engine/process/orders/StudyOrder.h \
    engine/process/orders/SwapOrder.h \
    engine/process/orders/SwapOrderRequest.h \
    engine/process/orders/SynchroOrder.h \
    engine/process/orders/SynchroOrderRequest.h \
    engine/process/orders/TacticOrder.h \
    engine/process/orders/TargetOrder.h \
    engine/process/orders/TeachOrder.h \
    engine/process/orders/UnstackOrder.h \
    engine/process/orders/UseOrder.h \
    engine/process/orders/WaitOrder.h \
    engine/process/orders/WithdrawOrder.h \
    engine/process/orders/WorkOrder.h \
    engine/process/orders/YieldOrder.h \
    engine/report/CombatReport.h \
    engine/report/ReportPattern.h \
    engine/report/ReportRecord.h \
    engine/report/TextsForReports.h \
    engine/report/patterns/BinaryMessage.h \
    engine/report/patterns/CombatAttackMessage.h \
    engine/report/patterns/CombatLootMessage.h \
    engine/report/patterns/CombatParticipantMessage.h \
    engine/report/patterns/EndLineMessage.h \
    engine/report/patterns/QuartenaryMessage.h \
    engine/report/patterns/QuintenaryMessage.h \
    engine/report/patterns/ReportMessage.h \
    engine/report/patterns/SimpleMessage.h \
    engine/report/patterns/TertiaryMessage.h \
    engine/report/patterns/UnaryMessage.h \
    engine/report/reporting.h \
    engine/DataManipulator.h \
    engine/GameConfig.h \
    engine/Global.h
SOURCES += engine/combat/BasicCombatEngine.cpp \
    engine/combat/BasicCombatManager.cpp \
    engine/combat/BasicCombatRequest.cpp \
    engine/combat/BattleEntity.cpp \
    engine/combat/BattleField.cpp \
    engine/combat/BattleInstance.cpp \
    engine/combat/BattleUnit.cpp \
    engine/combat/CombatEngine.cpp \
    engine/combat/CombatManager.cpp \
    engine/combat/CombatOrderProcessor.cpp \
    engine/combat/CombatTactics.cpp \
    engine/combat/GuardingRequest.cpp \
    engine/combat/PillageRequest.cpp \
    engine/combat/actions/MeleeCombatAction.cpp \
    engine/combat/actions/RangedCombatAction.cpp \
    engine/combat/actions/SpecialCombatAction.cpp \
    engine/combat/orders/AdvanceCombatOrder.cpp \
    engine/combat/orders/ApplyCombatOrder.cpp \
    engine/combat/orders/ChargeCombatOrder.cpp \
    engine/combat/orders/CombatOrderPrototype.cpp \
    engine/combat/orders/FireCombatOrder.cpp \
    engine/combat/orders/FlankCombatOrder.cpp \
    engine/combat/orders/FleeCombatOrder.cpp \
    engine/combat/orders/MeleeCombatOrder.cpp \
    engine/combat/orders/MoveCombatOrder.cpp \
    engine/combat/orders/ParryCombatOrder.cpp \
    engine/combat/orders/RangedCombatOrder.cpp \
    engine/combat/orders/RetreatCombatOrder.cpp \
    engine/combat/orders/StandCombatOrder.cpp \
    engine/combat/orders/SupportCombatOrder.cpp \
    engine/combat/orders/SweepCombatOrder.cpp \
    engine/combat/orders/UseCombatOrder.cpp \
    engine/datatypes/AbstractData.cpp \
    engine/datatypes/BasicData.cpp \
    engine/datatypes/GameData.cpp \
    engine/datatypes/IntegerData.cpp \
    engine/datatypes/PrototypeManager.cpp \
    engine/datatypes/RationalNumber.cpp \
    engine/datatypes/StringData.cpp \
    engine/datatypes/attributes/BasicAttribute.cpp \
    engine/datatypes/attributes/EnchantmentAttribute.cpp \
    engine/datatypes/attributes/InventoryAttribute.cpp \
    engine/datatypes/attributes/MovementBonusAttribute.cpp \
    engine/datatypes/attributes/OwnershipPolicyAttribute.cpp \
    engine/datatypes/attributes/PermissionAttribute.cpp \
    engine/datatypes/attributes/SkillBonusAttribute.cpp \
    engine/datatypes/attributes/SkillBonusComboAttribute.cpp \
    engine/datatypes/attributes/SkillsAttribute.cpp \
    engine/datatypes/attributes/TitlesAttribute.cpp \
    engine/datatypes/collections/BasicCollection.cpp \
    engine/datatypes/collections/BasicEntitiesCollection.cpp \
    engine/datatypes/collections/BasicRulesCollection.cpp \
    engine/datatypes/collections/BasicVarietiesCollection.cpp \
    engine/datatypes/collections/DataStorageHandler.cpp \
    engine/datatypes/collections/EntitiesCollection.cpp \
    engine/datatypes/collections/MovementMode.cpp \
    engine/datatypes/collections/OrderPrototypesCollection.cpp \
    engine/datatypes/collections/RulesCollection.cpp \
    engine/datatypes/collections/VarietiesCollection.cpp \
    engine/datatypes/conditions/BasicCondition.cpp \
    engine/datatypes/conditions/ObservationCondition.cpp \
    engine/datatypes/conditions/SkillCondition.cpp \
    engine/datatypes/elements/BonusElement.cpp \
    engine/datatypes/elements/ConstructionWorksElement.cpp \
    engine/datatypes/elements/EnchantmentElement.cpp \
    engine/datatypes/elements/FactionPermissionElement.cpp \
    engine/datatypes/elements/InventoryElement.cpp \
    engine/datatypes/elements/ItemElement.cpp \
    engine/datatypes/elements/MeleeAttackElement.cpp \
    engine/datatypes/elements/MovementBonusElement.cpp \
    engine/datatypes/elements/MovementElement.cpp \
    engine/datatypes/elements/PermissionElement.cpp \
    engine/datatypes/elements/RaceElement.cpp \
    engine/datatypes/elements/ReportElement.cpp \
    engine/datatypes/elements/ResourceElement.cpp \
    engine/datatypes/elements/SkillElement.cpp \
    engine/datatypes/elements/SkillUseElement.cpp \
    engine/datatypes/elements/StanceElement.cpp \
    engine/datatypes/elements/TitleElement.cpp \
    engine/datatypes/elements/ToolUseElement.cpp \
    engine/datatypes/elements/TravelElement.cpp \
    engine/datatypes/elements/TreeBonusElement.cpp \
    engine/datatypes/elements/WeatherElement.cpp \
    engine/datatypes/entities/ConstructionEntity.cpp \
    engine/datatypes/entities/EffectEntity.cpp \
    engine/datatypes/entities/Entity.cpp \
    engine/datatypes/entities/FactionEntity.cpp \
    engine/datatypes/entities/LocationEntity.cpp \
    engine/datatypes/entities/TokenEntity.cpp \
    engine/datatypes/entities/UnitEntity.cpp \
    engine/datatypes/misc/BasicExit.cpp \
    engine/datatypes/misc/EntityStatistics.cpp \
    engine/datatypes/misc/ExplicitExit.cpp \
    engine/datatypes/misc/NewEntityPlaceholder.cpp \
    engine/datatypes/misc/OwnershipPolicy.cpp \
    engine/datatypes/rules/ActionRule.cpp \
    engine/datatypes/rules/ConstructionRule.cpp \
    engine/datatypes/rules/CreatureRaceRule.cpp \
    engine/datatypes/rules/EnchantmentRule.cpp \
    engine/datatypes/rules/FollowerRaceRule.cpp \
    engine/datatypes/rules/ItemRule.cpp \
    engine/datatypes/rules/LeaderRaceRule.cpp \
    engine/datatypes/rules/RaceRule.cpp \
    engine/datatypes/rules/Rule.cpp \
    engine/datatypes/rules/RuleIndex.cpp \
    engine/datatypes/rules/SeasonRule.cpp \
    engine/datatypes/rules/SkillRule.cpp \
    engine/datatypes/rules/TerrainRule.cpp \
    engine/datatypes/rules/TitleRule.cpp \
    engine/datatypes/rules/WeatherRule.cpp \
    engine/datatypes/strategies/ActionUsingStrategy.cpp \
    engine/datatypes/strategies/BasicLearningStrategy.cpp \
    engine/datatypes/strategies/BasicProductionStrategy.cpp \
    engine/datatypes/strategies/BasicUsingStrategy.cpp \
    engine/datatypes/strategies/BuildUsingStrategy.cpp \
    engine/datatypes/strategies/CombatActionStrategy.cpp \
    engine/datatypes/strategies/CombatUsingStrategy.cpp \
    engine/datatypes/strategies/ConstructionUsingStrategy.cpp \
    engine/datatypes/strategies/CraftUsingStrategy.cpp \
    engine/datatypes/strategies/CreatureLearningStrategy.cpp \
    engine/datatypes/strategies/EnchantmentUsingStrategy.cpp \
    engine/datatypes/strategies/HarvestUsingStrategy.cpp \
    engine/datatypes/strategies/MagicLearningStrategy.cpp \
    engine/datatypes/strategies/MarketStrategy.cpp \
    engine/datatypes/strategies/NormalLearningStrategy.cpp \
    engine/datatypes/strategies/Strategy.cpp \
    engine/datatypes/strategies/SummonUsingStrategy.cpp \
    engine/datatypes/varieties/CombatFileVariety.cpp \
    engine/datatypes/varieties/CombatMoveVariety.cpp \
    engine/datatypes/varieties/CombatRankVariety.cpp \
    engine/datatypes/varieties/CombatStanceVariety.cpp \
    engine/datatypes/varieties/CombatTargetVariety.cpp \
    engine/datatypes/varieties/ConstructionWorksVariety.cpp \
    engine/datatypes/varieties/DirectionVariety.cpp \
    engine/datatypes/varieties/EquipmentSlotVariety.cpp \
    engine/datatypes/varieties/MovementVariety.cpp \
    engine/datatypes/varieties/StanceVariety.cpp \
    engine/datatypes/varieties/Variety.cpp \
    engine/implementation/actions/PickpocketActionRule.cpp \
    engine/implementation/combat/EnchantCombatAction.cpp \
    engine/implementation/combat/HeavinessCombatAction.cpp \
    engine/implementation/combat/SummonCombatAction.cpp \
    engine/misc/FileParser.cpp \
    engine/misc/LineParser.cpp \
    engine/misc/ReportPrinter.cpp \
    engine/misc/dgChannelBuf.cpp \
    engine/process/CombatOrderLine.cpp \
    engine/process/OrderLine.cpp \
    engine/process/OrderProcessor.cpp \
    engine/process/ProcessingMode.cpp \
    engine/process/conflicts/BasicCompetitiveRequest.cpp \
    engine/process/conflicts/BasicConflict.cpp \
    engine/process/conflicts/BasicRequest.cpp \
    engine/process/conflicts/EvenConflict.cpp \
    engine/process/conflicts/LocalMarketRequest.cpp \
    engine/process/conflicts/LocalRecruitOffer.cpp \
    engine/process/conflicts/MarketConflict.cpp \
    engine/process/conflicts/MarketRequest.cpp \
    engine/process/conflicts/NewRecruitRequest.cpp \
    engine/process/conflicts/RecruitRequest.cpp \
    engine/process/conflicts/ResourceCompetitiveRequest.cpp \
    engine/process/conflicts/TeachingOffer.cpp \
    engine/process/conflicts/WagesCompetitiveRequest.cpp \
    engine/process/orders/AcceptOrder.cpp \
    engine/process/orders/AtOrder.cpp \
    engine/process/orders/AttackOrder.cpp \
    engine/process/orders/BasicOrderSynchronizationRequest.cpp \
    engine/process/orders/BestowOrder.cpp \
    engine/process/orders/BuildOrder.cpp \
    engine/process/orders/BuyOrder.cpp \
    engine/process/orders/CancelOrder.cpp \
    engine/process/orders/CaravanOrder.cpp \
    engine/process/orders/ChristenOrder.cpp \
    engine/process/orders/ClaimOrder.cpp \
    engine/process/orders/CombatOrder.cpp \
    engine/process/orders/DayOrder.cpp \
    engine/process/orders/DescribeOrder.cpp \
    engine/process/orders/DisbandOrder.cpp \
    engine/process/orders/DropOrder.cpp \
    engine/process/orders/EjectOrder.cpp \
    engine/process/orders/EmailOrder.cpp \
    engine/process/orders/EnterOrder.cpp \
    engine/process/orders/EquipOrder.cpp \
    engine/process/orders/ExitOrder.cpp \
    engine/process/orders/ForgetOrder.cpp \
    engine/process/orders/GetOrder.cpp \
    engine/process/orders/GiveOrder.cpp \
    engine/process/orders/GuardOrder.cpp \
    engine/process/orders/HaveOrder.cpp \
    engine/process/orders/LeaderOrder.cpp \
    engine/process/orders/LeadingOrder.cpp \
    engine/process/orders/LeaveOrder.cpp \
    engine/process/orders/MarchOrder.cpp \
    engine/process/orders/MergeOrder.cpp \
    engine/process/orders/MoveOrder.cpp \
    engine/process/orders/NameOrder.cpp \
    engine/process/orders/OathOrder.cpp \
    engine/process/orders/OrderPrototype.cpp \
    engine/process/orders/PasswordOrder.cpp \
    engine/process/orders/PatrolOrder.cpp \
    engine/process/orders/PillageOrder.cpp \
    engine/process/orders/PromoteOrder.cpp \
    engine/process/orders/RecruitOrder.cpp \
    engine/process/orders/ReshowOrder.cpp \
    engine/process/orders/ResignOrder.cpp \
    engine/process/orders/RetreatOrder.cpp \
    engine/process/orders/SeeOrder.cpp \
    engine/process/orders/SellOrder.cpp \
    engine/process/orders/SettingOrder.cpp \
    engine/process/orders/SizeOrder.cpp \
    engine/process/orders/SkillOrder.cpp \
    engine/process/orders/SplitOrder.cpp \
    engine/process/orders/StackOrder.cpp \
    engine/process/orders/StanceOrder.cpp \
    engine/process/orders/StayOrder.cpp \
    engine/process/orders/StudyOrder.cpp \
    engine/process/orders/SwapOrder.cpp \
    engine/process/orders/SwapOrderRequest.cpp \
    engine/process/orders/SynchroOrder.cpp \
    engine/process/orders/SynchroOrderRequest.cpp \
    engine/process/orders/TacticOrder.cpp \
    engine/process/orders/TargetOrder.cpp \
    engine/process/orders/TeachOrder.cpp \
    engine/process/orders/UnstackOrder.cpp \
    engine/process/orders/UseOrder.cpp \
    engine/process/orders/WaitOrder.cpp \
    engine/process/orders/WithdrawOrder.cpp \
    engine/process/orders/WorkOrder.cpp \
    engine/process/orders/YieldOrder.cpp \
    engine/report/CombatReport.cpp \
    engine/report/ReportPattern.cpp \
    engine/report/ReportRecord.cpp \
    engine/report/TextsForReports.cpp \
    engine/report/patterns/BinaryMessage.cpp \
    engine/report/patterns/CombatAttackMessage.cpp \
    engine/report/patterns/CombatLootMessage.cpp \
    engine/report/patterns/CombatParticipantMessage.cpp \
    engine/report/patterns/EndLineMessage.cpp \
    engine/report/patterns/QuartenaryMessage.cpp \
    engine/report/patterns/QuintenaryMessage.cpp \
    engine/report/patterns/ReportMessage.cpp \
    engine/report/patterns/SimpleMessage.cpp \
    engine/report/patterns/TertiaryMessage.cpp \
    engine/report/patterns/UnaryMessage.cpp \
    engine/turn.cpp \
    engine/DataManipulator.cpp \
    engine/GameConfig.cpp \
    engine/Global.cpp
FORMS += 
RESOURCES += 
INCLUDEPATH += engine \
    engine/misc \
    engine/report \
    engine/report/patterns \
    engine/process \
    engine/process/orders \
    engine/process/conflicts \
    engine/implementation/combat \
    engine/implementation/actions \
    engine/datatypes \
    engine/datatypes/varieties \
    engine/datatypes/entities \
    engine/datatypes/strategies \
    engine/datatypes/rules \
    engine/datatypes/misc \
    engine/datatypes/elements \
    engine/datatypes/conditions \
    engine/datatypes/collections \
    engine/datatypes/attributes \
    engine/combat \
    engine/combat/orders \
    engine/combat/actions
QMAKE_CXXFLAGS = -DDEBUG \
    -W \
    -Wall \
    -Wno-unused \
    -Wno-sign-compare
