TEMPLATE = app
TARGET = QOverlordApp
QT += core \
    gui \
    network \
    webkit
HEADERS +=  combat/BasicCombatEngine.h \
     combat/BasicCombatManager.h \
     combat/BasicCombatRequest.h \
     combat/BattleEntity.h \
     combat/BattleField.h \
     combat/BattleInstance.h \
     combat/BattleUnit.h \
     combat/CombatEngine.h \
     combat/CombatManager.h \
     combat/CombatOrderProcessor.h \
     combat/CombatTactics.h \
     combat/GuardingRequest.h \
     combat/PillageRequest.h \
     combat/actions/MeleeCombatAction.h \
     combat/actions/RangedCombatAction.h \
     combat/actions/SpecialCombatAction.h \
     combat/orders/AdvanceCombatOrder.h \
     combat/orders/ApplyCombatOrder.h \
     combat/orders/ChargeCombatOrder.h \
     combat/orders/CombatOrderPrototype.h \
     combat/orders/FireCombatOrder.h \
     combat/orders/FlankCombatOrder.h \
     combat/orders/FleeCombatOrder.h \
     combat/orders/MeleeCombatOrder.h \
     combat/orders/MoveCombatOrder.h \
     combat/orders/ParryCombatOrder.h \
     combat/orders/RangedCombatOrder.h \
     combat/orders/RetreatCombatOrder.h \
     combat/orders/StandCombatOrder.h \
     combat/orders/SupportCombatOrder.h \
     combat/orders/SweepCombatOrder.h \
     combat/orders/UseCombatOrder.h \
     datatypes/AbstractData.h \
     datatypes/BasicData.h \
     datatypes/GameData.h \
     datatypes/IntegerData.h \
     datatypes/PrototypeManager.h \
     datatypes/RationalNumber.h \
     datatypes/StringData.h \
     datatypes/attributes/BasicAttribute.h \
     datatypes/attributes/EnchantmentAttribute.h \
     datatypes/attributes/InventoryAttribute.h \
     datatypes/attributes/MovementBonusAttribute.h \
     datatypes/attributes/OwnershipPolicyAttribute.h \
     datatypes/attributes/PermissionAttribute.h \
     datatypes/attributes/SkillBonusAttribute.h \
     datatypes/attributes/SkillBonusComboAttribute.h \
     datatypes/attributes/SkillsAttribute.h \
     datatypes/attributes/TitlesAttribute.h \
     datatypes/collections/BasicCollection.h \
     datatypes/collections/BasicEntitiesCollection.h \
     datatypes/collections/BasicRulesCollection.h \
     datatypes/collections/BasicVarietiesCollection.h \
     datatypes/collections/DataStorageHandler.h \
     datatypes/collections/EntitiesCollection.h \
     datatypes/collections/MovementMode.h \
     datatypes/collections/OrderPrototypesCollection.h \
     datatypes/collections/RulesCollection.h \
     datatypes/collections/VarietiesCollection.h \
     datatypes/conditions/BasicCondition.h \
     datatypes/conditions/ObservationCondition.h \
     datatypes/conditions/SkillCondition.h \
     datatypes/elements/BonusElement.h \
     datatypes/elements/ConstructionWorksElement.h \
     datatypes/elements/Element.h \
     datatypes/elements/EnchantmentElement.h \
     datatypes/elements/FactionPermissionElement.h \
     datatypes/elements/InventoryElement.h \
     datatypes/elements/ItemElement.h \
     datatypes/elements/MeleeAttackElement.h \
     datatypes/elements/MovementBonusElement.h \
     datatypes/elements/MovementElement.h \
     datatypes/elements/PermissionElement.h \
     datatypes/elements/RaceElement.h \
     datatypes/elements/ReportElement.h \
     datatypes/elements/ResourceElement.h \
     datatypes/elements/SkillElement.h \
     datatypes/elements/SkillLevelElement.h \
     datatypes/elements/SkillUseElement.h \
     datatypes/elements/StanceElement.h \
     datatypes/elements/TitleElement.h \
     datatypes/elements/ToolUseElement.h \
     datatypes/elements/TravelElement.h \
     datatypes/elements/TreeBonusElement.h \
     datatypes/elements/WeatherElement.h \
     datatypes/entities/ConstructionEntity.h \
     datatypes/entities/EffectEntity.h \
     datatypes/entities/Entity.h \
     datatypes/entities/FactionEntity.h \
     datatypes/entities/LocationEntity.h \
     datatypes/entities/TokenEntity.h \
     datatypes/entities/UnitEntity.h \
     datatypes/misc/BasicExit.h \
     datatypes/misc/EntityStatistics.h \
     datatypes/misc/ExplicitExit.h \
     datatypes/misc/NewEntityPlaceholder.h \
     datatypes/misc/OwnershipPolicy.h \
     datatypes/rules/ActionRule.h \
     datatypes/rules/ConstructionRule.h \
     datatypes/rules/CreatureRaceRule.h \
     datatypes/rules/EnchantmentRule.h \
     datatypes/rules/FollowerRaceRule.h \
     datatypes/rules/ItemRule.h \
     datatypes/rules/LeaderRaceRule.h \
     datatypes/rules/RaceRule.h \
     datatypes/rules/Rule.h \
     datatypes/rules/RuleIndex.h \
     datatypes/rules/SeasonRule.h \
     datatypes/rules/SkillRule.h \
     datatypes/rules/TerrainRule.h \
     datatypes/rules/TitleRule.h \
     datatypes/rules/WeatherRule.h \
     datatypes/strategies/ActionUsingStrategy.h \
     datatypes/strategies/BasicLearningStrategy.h \
     datatypes/strategies/BasicProductionStrategy.h \
     datatypes/strategies/BasicUsingStrategy.h \
     datatypes/strategies/BuildUsingStrategy.h \
     datatypes/strategies/CombatActionStrategy.h \
     datatypes/strategies/CombatUsingStrategy.h \
     datatypes/strategies/ConstructionUsingStrategy.h \
     datatypes/strategies/CraftUsingStrategy.h \
     datatypes/strategies/CreatureLearningStrategy.h \
     datatypes/strategies/EnchantmentUsingStrategy.h \
     datatypes/strategies/HarvestUsingStrategy.h \
     datatypes/strategies/MagicLearningStrategy.h \
     datatypes/strategies/MarketStrategy.h \
     datatypes/strategies/NormalLearningStrategy.h \
     datatypes/strategies/Strategy.h \
     datatypes/strategies/SummonUsingStrategy.h \
     datatypes/varieties/CombatFileVariety.h \
     datatypes/varieties/CombatMoveVariety.h \
     datatypes/varieties/CombatRankVariety.h \
     datatypes/varieties/CombatStanceVariety.h \
     datatypes/varieties/CombatTargetVariety.h \
     datatypes/varieties/ConstructionWorksVariety.h \
     datatypes/varieties/DirectionVariety.h \
     datatypes/varieties/EquipmentSlotVariety.h \
     datatypes/varieties/MovementVariety.h \
     datatypes/varieties/StanceVariety.h \
     datatypes/varieties/Variety.h \
     implementation/actions/PickpocketActionRule.h \
     implementation/combat/EnchantCombatAction.h \
     implementation/combat/HeavinessCombatAction.h \
     implementation/combat/SummonCombatAction.h \
     misc/FileParser.h \
     misc/LineParser.h \
     misc/OverlordTypes.h \
     misc/ReportPrinter.h \
     misc/Symbols.h \
     misc/SystemTypes.h \
     misc/dgChannelBuf.h \
     process/CombatOrderLine.h \
     process/OrderLine.h \
     process/OrderProcessor.h \
     process/ProcessingMode.h \
     process/conflicts/BasicCompetitiveRequest.h \
     process/conflicts/BasicConflict.h \
     process/conflicts/BasicRequest.h \
     process/conflicts/EvenConflict.h \
     process/conflicts/LocalMarketRequest.h \
     process/conflicts/LocalRecruitOffer.h \
     process/conflicts/MarketConflict.h \
     process/conflicts/MarketRequest.h \
     process/conflicts/NewRecruitRequest.h \
     process/conflicts/RecruitRequest.h \
     process/conflicts/ResourceCompetitiveRequest.h \
     process/conflicts/TeachingOffer.h \
     process/conflicts/WagesCompetitiveRequest.h \
     process/orders/AcceptOrder.h \
     process/orders/AtOrder.h \
     process/orders/AttackOrder.h \
     process/orders/BasicOrderSynchronizationRequest.h \
     process/orders/BestowOrder.h \
     process/orders/BuildOrder.h \
     process/orders/BuyOrder.h \
     process/orders/CancelOrder.h \
     process/orders/CaravanOrder.h \
     process/orders/ChristenOrder.h \
     process/orders/ClaimOrder.h \
     process/orders/CombatOrder.h \
     process/orders/DayOrder.h \
     process/orders/DescribeOrder.h \
     process/orders/DisbandOrder.h \
     process/orders/DropOrder.h \
     process/orders/EjectOrder.h \
     process/orders/EmailOrder.h \
     process/orders/EnterOrder.h \
     process/orders/EquipOrder.h \
     process/orders/ExitOrder.h \
     process/orders/ForgetOrder.h \
     process/orders/GetOrder.h \
     process/orders/GiveOrder.h \
     process/orders/GuardOrder.h \
     process/orders/HaveOrder.h \
     process/orders/LeaderOrder.h \
     process/orders/LeadingOrder.h \
     process/orders/LeaveOrder.h \
     process/orders/MarchOrder.h \
     process/orders/MergeOrder.h \
     process/orders/MoveOrder.h \
     process/orders/NameOrder.h \
     process/orders/OathOrder.h \
     process/orders/OrderPrototype.h \
     process/orders/PasswordOrder.h \
     process/orders/PatrolOrder.h \
     process/orders/PillageOrder.h \
     process/orders/PromoteOrder.h \
     process/orders/RecruitOrder.h \
     process/orders/ReshowOrder.h \
     process/orders/ResignOrder.h \
     process/orders/RetreatOrder.h \
     process/orders/SeeOrder.h \
     process/orders/SellOrder.h \
     process/orders/SettingOrder.h \
     process/orders/SizeOrder.h \
     process/orders/SkillOrder.h \
     process/orders/SplitOrder.h \
     process/orders/StackOrder.h \
     process/orders/StanceOrder.h \
     process/orders/StayOrder.h \
     process/orders/StudyOrder.h \
     process/orders/SwapOrder.h \
     process/orders/SwapOrderRequest.h \
     process/orders/SynchroOrder.h \
     process/orders/SynchroOrderRequest.h \
     process/orders/TacticOrder.h \
     process/orders/TargetOrder.h \
     process/orders/TeachOrder.h \
     process/orders/UnstackOrder.h \
     process/orders/UseOrder.h \
     process/orders/WaitOrder.h \
     process/orders/WithdrawOrder.h \
     process/orders/WorkOrder.h \
     process/orders/YieldOrder.h \
     report/CombatReport.h \
     report/ReportPattern.h \
     report/ReportRecord.h \
     report/TextsForReports.h \
     report/patterns/BinaryMessage.h \
     report/patterns/CombatAttackMessage.h \
     report/patterns/CombatLootMessage.h \
     report/patterns/CombatParticipantMessage.h \
     report/patterns/EndLineMessage.h \
     report/patterns/QuartenaryMessage.h \
     report/patterns/QuintenaryMessage.h \
     report/patterns/ReportMessage.h \
     report/patterns/SimpleMessage.h \
     report/patterns/TertiaryMessage.h \
     report/patterns/UnaryMessage.h \
     report/reporting.h \
     DataManipulator.h \
     GameConfig.h \
     Global.h
SOURCES +=  combat/BasicCombatEngine.cpp \
     combat/BasicCombatManager.cpp \
     combat/BasicCombatRequest.cpp \
     combat/BattleEntity.cpp \
     combat/BattleField.cpp \
     combat/BattleInstance.cpp \
     combat/BattleUnit.cpp \
     combat/CombatEngine.cpp \
     combat/CombatManager.cpp \
     combat/CombatOrderProcessor.cpp \
     combat/CombatTactics.cpp \
     combat/GuardingRequest.cpp \
     combat/PillageRequest.cpp \
     combat/actions/MeleeCombatAction.cpp \
     combat/actions/RangedCombatAction.cpp \
     combat/actions/SpecialCombatAction.cpp \
     combat/orders/AdvanceCombatOrder.cpp \
     combat/orders/ApplyCombatOrder.cpp \
     combat/orders/ChargeCombatOrder.cpp \
     combat/orders/CombatOrderPrototype.cpp \
     combat/orders/FireCombatOrder.cpp \
     combat/orders/FlankCombatOrder.cpp \
     combat/orders/FleeCombatOrder.cpp \
     combat/orders/MeleeCombatOrder.cpp \
     combat/orders/MoveCombatOrder.cpp \
     combat/orders/ParryCombatOrder.cpp \
     combat/orders/RangedCombatOrder.cpp \
     combat/orders/RetreatCombatOrder.cpp \
     combat/orders/StandCombatOrder.cpp \
     combat/orders/SupportCombatOrder.cpp \
     combat/orders/SweepCombatOrder.cpp \
     combat/orders/UseCombatOrder.cpp \
     datatypes/AbstractData.cpp \
     datatypes/BasicData.cpp \
     datatypes/GameData.cpp \
     datatypes/IntegerData.cpp \
     datatypes/PrototypeManager.cpp \
     datatypes/RationalNumber.cpp \
     datatypes/StringData.cpp \
     datatypes/attributes/BasicAttribute.cpp \
     datatypes/attributes/EnchantmentAttribute.cpp \
     datatypes/attributes/InventoryAttribute.cpp \
     datatypes/attributes/MovementBonusAttribute.cpp \
     datatypes/attributes/OwnershipPolicyAttribute.cpp \
     datatypes/attributes/PermissionAttribute.cpp \
     datatypes/attributes/SkillBonusAttribute.cpp \
     datatypes/attributes/SkillBonusComboAttribute.cpp \
     datatypes/attributes/SkillsAttribute.cpp \
     datatypes/attributes/TitlesAttribute.cpp \
     datatypes/collections/BasicCollection.cpp \
     datatypes/collections/BasicEntitiesCollection.cpp \
     datatypes/collections/BasicRulesCollection.cpp \
     datatypes/collections/BasicVarietiesCollection.cpp \
     datatypes/collections/DataStorageHandler.cpp \
     datatypes/collections/EntitiesCollection.cpp \
     datatypes/collections/MovementMode.cpp \
     datatypes/collections/OrderPrototypesCollection.cpp \
     datatypes/collections/RulesCollection.cpp \
     datatypes/collections/VarietiesCollection.cpp \
     datatypes/conditions/BasicCondition.cpp \
     datatypes/conditions/ObservationCondition.cpp \
     datatypes/conditions/SkillCondition.cpp \
     datatypes/elements/BonusElement.cpp \
     datatypes/elements/ConstructionWorksElement.cpp \
     datatypes/elements/EnchantmentElement.cpp \
     datatypes/elements/FactionPermissionElement.cpp \
     datatypes/elements/InventoryElement.cpp \
     datatypes/elements/ItemElement.cpp \
     datatypes/elements/MeleeAttackElement.cpp \
     datatypes/elements/MovementBonusElement.cpp \
     datatypes/elements/MovementElement.cpp \
     datatypes/elements/PermissionElement.cpp \
     datatypes/elements/RaceElement.cpp \
     datatypes/elements/ReportElement.cpp \
     datatypes/elements/ResourceElement.cpp \
     datatypes/elements/SkillElement.cpp \
     datatypes/elements/SkillUseElement.cpp \
     datatypes/elements/StanceElement.cpp \
     datatypes/elements/TitleElement.cpp \
     datatypes/elements/ToolUseElement.cpp \
     datatypes/elements/TravelElement.cpp \
     datatypes/elements/TreeBonusElement.cpp \
     datatypes/elements/WeatherElement.cpp \
     datatypes/entities/ConstructionEntity.cpp \
     datatypes/entities/EffectEntity.cpp \
     datatypes/entities/Entity.cpp \
     datatypes/entities/FactionEntity.cpp \
     datatypes/entities/LocationEntity.cpp \
     datatypes/entities/TokenEntity.cpp \
     datatypes/entities/UnitEntity.cpp \
     datatypes/misc/BasicExit.cpp \
     datatypes/misc/EntityStatistics.cpp \
     datatypes/misc/ExplicitExit.cpp \
     datatypes/misc/NewEntityPlaceholder.cpp \
     datatypes/misc/OwnershipPolicy.cpp \
     datatypes/rules/ActionRule.cpp \
     datatypes/rules/ConstructionRule.cpp \
     datatypes/rules/CreatureRaceRule.cpp \
     datatypes/rules/EnchantmentRule.cpp \
     datatypes/rules/FollowerRaceRule.cpp \
     datatypes/rules/ItemRule.cpp \
     datatypes/rules/LeaderRaceRule.cpp \
     datatypes/rules/RaceRule.cpp \
     datatypes/rules/Rule.cpp \
     datatypes/rules/RuleIndex.cpp \
     datatypes/rules/SeasonRule.cpp \
     datatypes/rules/SkillRule.cpp \
     datatypes/rules/TerrainRule.cpp \
     datatypes/rules/TitleRule.cpp \
     datatypes/rules/WeatherRule.cpp \
     datatypes/strategies/ActionUsingStrategy.cpp \
     datatypes/strategies/BasicLearningStrategy.cpp \
     datatypes/strategies/BasicProductionStrategy.cpp \
     datatypes/strategies/BasicUsingStrategy.cpp \
     datatypes/strategies/BuildUsingStrategy.cpp \
     datatypes/strategies/CombatActionStrategy.cpp \
     datatypes/strategies/CombatUsingStrategy.cpp \
     datatypes/strategies/ConstructionUsingStrategy.cpp \
     datatypes/strategies/CraftUsingStrategy.cpp \
     datatypes/strategies/CreatureLearningStrategy.cpp \
     datatypes/strategies/EnchantmentUsingStrategy.cpp \
     datatypes/strategies/HarvestUsingStrategy.cpp \
     datatypes/strategies/MagicLearningStrategy.cpp \
     datatypes/strategies/MarketStrategy.cpp \
     datatypes/strategies/NormalLearningStrategy.cpp \
     datatypes/strategies/Strategy.cpp \
     datatypes/strategies/SummonUsingStrategy.cpp \
     datatypes/varieties/CombatFileVariety.cpp \
     datatypes/varieties/CombatMoveVariety.cpp \
     datatypes/varieties/CombatRankVariety.cpp \
     datatypes/varieties/CombatStanceVariety.cpp \
     datatypes/varieties/CombatTargetVariety.cpp \
     datatypes/varieties/ConstructionWorksVariety.cpp \
     datatypes/varieties/DirectionVariety.cpp \
     datatypes/varieties/EquipmentSlotVariety.cpp \
     datatypes/varieties/MovementVariety.cpp \
     datatypes/varieties/StanceVariety.cpp \
     datatypes/varieties/Variety.cpp \
     implementation/actions/PickpocketActionRule.cpp \
     implementation/combat/EnchantCombatAction.cpp \
     implementation/combat/HeavinessCombatAction.cpp \
     implementation/combat/SummonCombatAction.cpp \
     misc/FileParser.cpp \
     misc/LineParser.cpp \
     misc/ReportPrinter.cpp \
     misc/dgChannelBuf.cpp \
     process/CombatOrderLine.cpp \
     process/OrderLine.cpp \
     process/OrderProcessor.cpp \
     process/ProcessingMode.cpp \
     process/conflicts/BasicCompetitiveRequest.cpp \
     process/conflicts/BasicConflict.cpp \
     process/conflicts/BasicRequest.cpp \
     process/conflicts/EvenConflict.cpp \
     process/conflicts/LocalMarketRequest.cpp \
     process/conflicts/LocalRecruitOffer.cpp \
     process/conflicts/MarketConflict.cpp \
     process/conflicts/MarketRequest.cpp \
     process/conflicts/NewRecruitRequest.cpp \
     process/conflicts/RecruitRequest.cpp \
     process/conflicts/ResourceCompetitiveRequest.cpp \
     process/conflicts/TeachingOffer.cpp \
     process/conflicts/WagesCompetitiveRequest.cpp \
     process/orders/AcceptOrder.cpp \
     process/orders/AtOrder.cpp \
     process/orders/AttackOrder.cpp \
     process/orders/BasicOrderSynchronizationRequest.cpp \
     process/orders/BestowOrder.cpp \
     process/orders/BuildOrder.cpp \
     process/orders/BuyOrder.cpp \
     process/orders/CancelOrder.cpp \
     process/orders/CaravanOrder.cpp \
     process/orders/ChristenOrder.cpp \
     process/orders/ClaimOrder.cpp \
     process/orders/CombatOrder.cpp \
     process/orders/DayOrder.cpp \
     process/orders/DescribeOrder.cpp \
     process/orders/DisbandOrder.cpp \
     process/orders/DropOrder.cpp \
     process/orders/EjectOrder.cpp \
     process/orders/EmailOrder.cpp \
     process/orders/EnterOrder.cpp \
     process/orders/EquipOrder.cpp \
     process/orders/ExitOrder.cpp \
     process/orders/ForgetOrder.cpp \
     process/orders/GetOrder.cpp \
     process/orders/GiveOrder.cpp \
     process/orders/GuardOrder.cpp \
     process/orders/HaveOrder.cpp \
     process/orders/LeaderOrder.cpp \
     process/orders/LeadingOrder.cpp \
     process/orders/LeaveOrder.cpp \
     process/orders/MarchOrder.cpp \
     process/orders/MergeOrder.cpp \
     process/orders/MoveOrder.cpp \
     process/orders/NameOrder.cpp \
     process/orders/OathOrder.cpp \
     process/orders/OrderPrototype.cpp \
     process/orders/PasswordOrder.cpp \
     process/orders/PatrolOrder.cpp \
     process/orders/PillageOrder.cpp \
     process/orders/PromoteOrder.cpp \
     process/orders/RecruitOrder.cpp \
     process/orders/ReshowOrder.cpp \
     process/orders/ResignOrder.cpp \
     process/orders/RetreatOrder.cpp \
     process/orders/SeeOrder.cpp \
     process/orders/SellOrder.cpp \
     process/orders/SettingOrder.cpp \
     process/orders/SizeOrder.cpp \
     process/orders/SkillOrder.cpp \
     process/orders/SplitOrder.cpp \
     process/orders/StackOrder.cpp \
     process/orders/StanceOrder.cpp \
     process/orders/StayOrder.cpp \
     process/orders/StudyOrder.cpp \
     process/orders/SwapOrder.cpp \
     process/orders/SwapOrderRequest.cpp \
     process/orders/SynchroOrder.cpp \
     process/orders/SynchroOrderRequest.cpp \
     process/orders/TacticOrder.cpp \
     process/orders/TargetOrder.cpp \
     process/orders/TeachOrder.cpp \
     process/orders/UnstackOrder.cpp \
     process/orders/UseOrder.cpp \
     process/orders/WaitOrder.cpp \
     process/orders/WithdrawOrder.cpp \
     process/orders/WorkOrder.cpp \
     process/orders/YieldOrder.cpp \
     report/CombatReport.cpp \
     report/ReportPattern.cpp \
     report/ReportRecord.cpp \
     report/TextsForReports.cpp \
     report/patterns/BinaryMessage.cpp \
     report/patterns/CombatAttackMessage.cpp \
     report/patterns/CombatLootMessage.cpp \
     report/patterns/CombatParticipantMessage.cpp \
     report/patterns/EndLineMessage.cpp \
     report/patterns/QuartenaryMessage.cpp \
     report/patterns/QuintenaryMessage.cpp \
     report/patterns/ReportMessage.cpp \
     report/patterns/SimpleMessage.cpp \
     report/patterns/TertiaryMessage.cpp \
     report/patterns/UnaryMessage.cpp \
     turn.cpp \
     DataManipulator.cpp \
     GameConfig.cpp \
     Global.cpp
FORMS += 
RESOURCES += 
INCLUDEPATH += engine \
     misc \
     report \
     report/patterns \
     process \
     process/orders \
     process/conflicts \
     implementation/combat \
     implementation/actions \
     datatypes \
     datatypes/varieties \
     datatypes/entities \
     datatypes/strategies \
     datatypes/rules \
     datatypes/misc \
     datatypes/elements \
     datatypes/conditions \
     datatypes/collections \
     datatypes/attributes \
     combat \
     combat/orders \
     combat/actions
QMAKE_CXXFLAGS = -DDEBUG \
    -W \
    -Wall \
    -Wno-unused \
    -Wno-sign-compare
