######################## Compilation dependency #########################
ENGINE_SOURCES =  GameFacade.cpp \
          DataManipulator.cpp \
          GameConfig.cpp \
          Global.cpp \
          combat/BasicCombatEngine.cpp \
          combat/BasicCombatManager.cpp \
          combat/BasicCombatRequest.cpp \
          combat/CombatManager.cpp \
          combat/CombatTactics.cpp \
          combat/GuardingRequest.cpp \
          combat/PillageRequest.cpp \
	  combat/BattleUnit.cpp \
	  combat/BattleInstance.cpp \
	  combat/CombatEngine.cpp \
	  combat/CombatOrderProcessor.cpp \
	  combat/BattleField.cpp \
	  combat/BattleEntity.cpp \
	  combat/orders/ParryCombatOrder.cpp \
	  combat/orders/MoveCombatOrder.cpp \
	  combat/orders/FleeCombatOrder.cpp \
	  combat/orders/CombatOrderPrototype.cpp \
	  combat/orders/ChargeCombatOrder.cpp \
	  combat/orders/AdvanceCombatOrder.cpp \
	  combat/orders/MeleeCombatOrder.cpp \
	  combat/orders/FireCombatOrder.cpp \
	  combat/orders/FlankCombatOrder.cpp \
	  combat/orders/RangedCombatOrder.cpp \
	  combat/orders/RetreatCombatOrder.cpp \
	  combat/orders/StandCombatOrder.cpp \
	  combat/orders/SupportCombatOrder.cpp \
	  combat/orders/SweepCombatOrder.cpp \
	  combat/orders/UseCombatOrder.cpp \
	  combat/orders/ApplyCombatOrder.cpp \
	  combat/actions/MeleeCombatAction.cpp \
	  combat/actions/RangedCombatAction.cpp \
	  combat/actions/SpecialCombatAction.cpp \
          datatypes/attributes/BasicAttribute.cpp \
          datatypes/attributes/EnchantmentAttribute.cpp \
          datatypes/attributes/InventoryAttribute.cpp \
          datatypes/attributes/OwnershipPolicyAttribute.cpp \
          datatypes/attributes/PermissionAttribute.cpp \
          datatypes/attributes/MovementBonusAttribute.cpp \
          datatypes/attributes/SkillBonusAttribute.cpp \
          datatypes/attributes/SkillBonusComboAttribute.cpp \
          datatypes/attributes/SkillsAttribute.cpp \
          datatypes/attributes/TitlesAttribute.cpp \
          datatypes/AbstractData.cpp \
          datatypes/GameData.cpp \
          datatypes/IntegerData.cpp \
          datatypes/PrototypeManager.cpp \
          datatypes/RationalNumber.cpp \
          datatypes/StringData.cpp \
          datatypes/collections/BasicCollection.cpp \
          datatypes/collections/BasicEntitiesCollection.cpp \
          datatypes/collections/BasicEventsCollection.cpp \
          datatypes/collections/BasicRulesCollection.cpp \
          datatypes/collections/BasicVarietiesCollection.cpp \
          datatypes/collections/DataStorageHandler.cpp \
          datatypes/collections/EntitiesCollection.cpp \
          datatypes/collections/MovementMode.cpp \
          datatypes/collections/OrderPrototypesCollection.cpp \
          datatypes/collections/RulesCollection.cpp \
          datatypes/collections/VarietiesCollection.cpp \
          datatypes/conditions/BasicCondition.cpp \
          datatypes/conditions/CompositeCondition.cpp \
          datatypes/conditions/ObservationCondition.cpp \
          datatypes/conditions/SkillCondition.cpp \
          datatypes/conditions/StanceCondition.cpp \
          datatypes/elements/BonusElement.cpp \
          datatypes/elements/ConstructionWorksElement.cpp \
          datatypes/elements/EnchantmentElement.cpp \
          datatypes/elements/EventElement.cpp \
          datatypes/elements/InventoryElement.cpp \
          datatypes/elements/ItemElement.cpp \
	  datatypes/elements/MeleeAttackElement.cpp \
          datatypes/elements/MovementElement.cpp \
          datatypes/elements/MovementBonusElement.cpp \
          datatypes/elements/RaceElement.cpp \
          datatypes/elements/ReportElement.cpp \
          datatypes/elements/ResourceElement.cpp \
          datatypes/elements/SkillElement.cpp \
          datatypes/elements/SkillUseElement.cpp \
          datatypes/elements/StanceElement.cpp \
          datatypes/elements/TitleElement.cpp \
          datatypes/elements/ToolUseElement.cpp \
          datatypes/elements/TravelElement.cpp \
          datatypes/elements/TreeBonusElement.cpp \
          datatypes/elements/FactionPermissionElement.cpp \
          datatypes/elements/PermissionElement.cpp \
          datatypes/entities/TokenEntity.cpp \
          datatypes/entities/ConstructionEntity.cpp \
          datatypes/entities/EffectEntity.cpp \
          datatypes/entities/Entity.cpp \
          datatypes/entities/FactionEntity.cpp \
          datatypes/entities/LocationEntity.cpp \
          datatypes/entities/UnitEntity.cpp \
          datatypes/entities/UnknownUnitEntity.cpp \
          datatypes/events/Event.cpp \
          datatypes/misc/BasicExit.cpp \
          datatypes/misc/EntityStatistics.cpp \
          datatypes/misc/ExplicitExit.cpp \
          datatypes/misc/NewEntityPlaceholder.cpp \
          datatypes/misc/OwnershipPolicy.cpp \
          datatypes/misc/TimeStamp.cpp \
          datatypes/rules/RuleIndex.cpp \
          datatypes/rules/ActionRule.cpp \
          datatypes/rules/ConstructionRule.cpp \
          datatypes/rules/CreatureRaceRule.cpp \
          datatypes/rules/EffectRule.cpp \
          datatypes/rules/EnchantmentRule.cpp \
          datatypes/rules/EventRule.cpp \
          datatypes/rules/FollowerRaceRule.cpp \
          datatypes/rules/ItemRule.cpp \
          datatypes/rules/LeaderRaceRule.cpp \
          datatypes/rules/RaceRule.cpp \
          datatypes/rules/Rule.cpp \
          datatypes/rules/SkillRule.cpp \
          datatypes/rules/TerrainRule.cpp \
          datatypes/rules/TitleRule.cpp \
          datatypes/rules/WeatherRule.cpp \
          datatypes/rules/SeasonRule.cpp \
          datatypes/strategies/ActionUsingStrategy.cpp \
          datatypes/strategies/BasicLearningStrategy.cpp \
          datatypes/strategies/BasicProductionStrategy.cpp \
          datatypes/strategies/BasicUsingStrategy.cpp \
          datatypes/strategies/BuildUsingStrategy.cpp \
          datatypes/strategies/CombatActionStrategy.cpp \
          datatypes/strategies/CombatUsingStrategy.cpp \
          datatypes/strategies/ConstructionUsingStrategy.cpp \
          datatypes/strategies/CraftUsingStrategy.cpp \
          datatypes/strategies/CreatureLearningStrategy.cpp \
          datatypes/strategies/EnchantmentUsingStrategy.cpp \
          datatypes/strategies/HarvestUsingStrategy.cpp \
          datatypes/strategies/MagicLearningStrategy.cpp \
          datatypes/strategies/MarketStrategy.cpp \
          datatypes/strategies/NormalLearningStrategy.cpp \
          datatypes/strategies/Strategy.cpp \
          datatypes/strategies/SummonUsingStrategy.cpp \
          datatypes/varieties/ConstructionWorksVariety.cpp \
          datatypes/varieties/DirectionVariety.cpp \
          datatypes/varieties/EquipmentSlotVariety.cpp \
          datatypes/varieties/MovementVariety.cpp \
          datatypes/varieties/StanceVariety.cpp \
          datatypes/varieties/Variety.cpp \
          datatypes/varieties/CombatFileVariety.cpp \
          datatypes/varieties/CombatMoveVariety.cpp \
          datatypes/varieties/CombatRankVariety.cpp \
          datatypes/varieties/CombatStanceVariety.cpp \
          datatypes/varieties/CombatTargetVariety.cpp \
          implementation/actions/InfectionActionRule.cpp \
          implementation/actions/BuryActionRule.cpp \
          implementation/actions/PickpocketActionRule.cpp \
          implementation/actions/AffectWeatherAction.cpp \
          implementation/actions/CreatePortalAction.cpp \
          implementation/actions/AssassinateAction.cpp \
          implementation/actions/TerraformAction.cpp \
          implementation/actions/TransformAction.cpp \
          implementation/actions/RitualActionRule.cpp \
          implementation/combat/HeavinessCombatAction.cpp \
          implementation/combat/EnchantCombatAction.cpp \
          implementation/combat/SummonCombatAction.cpp \
	  implementation/effects/PlagueEffect.cpp \
          misc/FileParser.cpp \
          misc/LineParser.cpp \
          misc/ReportPrinter.cpp \
          misc/dgChannelBuf.cpp \
          process/conflicts/BasicRequest.cpp \
          process/conflicts/BasicCompetitiveRequest.cpp \
          process/conflicts/BasicConflict.cpp \
          process/conflicts/EvenConflict.cpp \
          process/conflicts/LocalMarketRequest.cpp \
          process/conflicts/LocalRecruitOffer.cpp \
          process/conflicts/MarketConflict.cpp \
          process/conflicts/MarketRequest.cpp \
          process/conflicts/NewRecruitRequest.cpp \
          process/conflicts/RecruitRequest.cpp \
          process/conflicts/ResourceCompetitiveRequest.cpp \
          process/conflicts/TeachingOffer.cpp \
          process/conflicts/WagesCompetitiveRequest.cpp \
          process/OrderLine.cpp \
          process/ProcessingMode.cpp \
          process/OrderProcessor.cpp \
          process/CombatOrderLine.cpp \
          process/orders/TacticOrder.cpp \
          process/orders/AcceptOrder.cpp \
          process/orders/AtOrder.cpp \
          process/orders/AttackOrder.cpp \
          process/orders/BasicOrderSynchronizationRequest.cpp \
          process/orders/BestowOrder.cpp \
          process/orders/BuyOrder.cpp \
          process/orders/CancelOrder.cpp \
          process/orders/CaravanOrder.cpp \
          process/orders/ChristenOrder.cpp \
          process/orders/ClaimOrder.cpp \
          process/orders/CombatOrder.cpp \
	  process/orders/DayOrder.cpp \
          process/orders/DescribeOrder.cpp \
          process/orders/DisbandOrder.cpp \
          process/orders/DropOrder.cpp \
          process/orders/EjectOrder.cpp \
          process/orders/EmailOrder.cpp \
          process/orders/EnterOrder.cpp \
          process/orders/EquipOrder.cpp \
          process/orders/ExitOrder.cpp \
          process/orders/ForgetOrder.cpp \
          process/orders/GetOrder.cpp \
          process/orders/GiveOrder.cpp \
          process/orders/GuardOrder.cpp \
          process/orders/HaveOrder.cpp \
          process/orders/LeaderOrder.cpp \
          process/orders/LeadingOrder.cpp \
          process/orders/LeaveOrder.cpp \
          process/orders/MarchOrder.cpp \
          process/orders/MergeOrder.cpp \
          process/orders/MoveOrder.cpp \
          process/orders/NameOrder.cpp \
          process/orders/OathOrder.cpp \
          process/orders/OrderPrototype.cpp \
          process/orders/PasswordOrder.cpp \
          process/orders/PatrolOrder.cpp \
          process/orders/PillageOrder.cpp \
          process/orders/PromoteOrder.cpp \
          process/orders/RecruitOrder.cpp \
          process/orders/ReshowOrder.cpp \
          process/orders/ResignOrder.cpp \
          process/orders/RetreatOrder.cpp \
          process/orders/SeeOrder.cpp \
          process/orders/SellOrder.cpp \
          process/orders/SettingOrder.cpp \
          process/orders/SizeOrder.cpp \
          process/orders/SkillOrder.cpp \
          process/orders/SplitOrder.cpp \
          process/orders/StackOrder.cpp \
          process/orders/StanceOrder.cpp \
          process/orders/StayOrder.cpp \
          process/orders/StudyOrder.cpp \
          process/orders/SwapOrder.cpp \
          process/orders/SwapOrderRequest.cpp \
          process/orders/SynchroOrder.cpp \
          process/orders/SynchroOrderRequest.cpp \
          process/orders/TargetOrder.cpp \
          process/orders/TeachOrder.cpp \
          process/orders/UnstackOrder.cpp \
          process/orders/UseOrder.cpp \
          process/orders/WaitOrder.cpp \
          process/orders/WithdrawOrder.cpp \
          process/orders/WorkOrder.cpp \
          process/orders/YieldOrder.cpp \
          report/patterns/BinaryMessage.cpp \
	  report/patterns/CombatParticipantMessage.cpp \
          report/patterns/CombatAttackMessage.cpp \
          report/patterns/CombatLootMessage.cpp \
          report/patterns/QuartenaryMessage.cpp \
          report/patterns/QuintenaryMessage.cpp \
          report/patterns/ReportMessage.cpp \
          report/patterns/SimpleMessage.cpp \
          report/patterns/TertiaryMessage.cpp \
          report/patterns/UnaryMessage.cpp \
          report/patterns/EndLineMessage.cpp \
          report/CombatReport.cpp \
          report/ReportPattern.cpp \
          report/ReportRecord.cpp \
          report/TextsForReports.cpp \
          report/TurnReport.cpp \